name: OneDrive sync Rclone
on:
#  push:
#    branches:
#      - master
  schedule:
    #- cron: 0 */6 * * *
  workflow_dispatch:
    inputs:
    
jobs:
  onedrive_sync:
    runs-on: ubuntu-latest
    name: gd sync

    steps:
      - uses: actions/checkout@v2
      - name: Rclone Install
        run: curl https://rclone.org/install.sh | sudo bash
        
      - name: Rclone Config
        run: |
          mkdir -p ~/.config/rclone/
          cat >  ~/.config/rclone/rclone.conf  << EOF
          ${{ secrets.RCLONE_CONF }}
          EOF

      - name: Rclone Run
        run: |
          rclone sync ${{ secrets.SOURCE_DEST }} --drive-server-side-across-configs --max-size 15G --transfers 16 --checkers 32 --checksum --stats-one-line-date -q
          echo "同步完成"
